import TransitionProvider from './components/TransitionProvider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'FARDAN KHAN | PORTFOLIO',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/hero1.png" as="image" />
        <link
          rel="icon"
          href="https://static.vecteezy.com/system/resources/thumbnails/017/426/170/small/modern-fk-logo-design-for-business-and-company-identity-creative-fk-letter-with-luxury-concept-vector.jpg"
          type="image/png"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
